spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diplomdb?useSSL=false
    username: root
    password: Energotehno202111101983KE7
  jpa:
    hibernate:
      ddl-auto: none

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: leshabosovec@mail.ru
  copyright: Алексей Босовец
  copyrightFrom: 2005